version: '3'
services:
  web:
    build: .
    volumes: 
      - "./html:/var/www/html"
    restart: always
    ports:
      - "80:80"
    networks:
      my_net:
        ipv4_address: 172.16.243.5
    depends_on:
      - db
      - ldap
  db:
    container_name: dbserver
    volumes: 
      - ./datadump.sql:/docker-entrypoint-initdb.d/datadump.sql 
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
    networks:
      my_net:
        ipv4_address: 172.16.243.6
networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.243.0/24"
          gateway: "172.16.243.1"
