version: '3'
services:
  web:
    build: .
    volumes: 
      - "./html:/var/www/html"
    restart: always
    ports:
      - "80:80"
    networks:
      my_net:
        ipv4_address: 172.16.243.5
    depends_on:
      - db
      - ldap
  db:
    container_name: dbserver
    volumes: 
      - ./datadump.sql:/docker-entrypoint-initdb.d/datadump.sql 
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_USER: test
      MYSQL_PASSWORD: test1234
    networks:
      my_net:
        ipv4_address: 172.16.243.6
  ldap:
    container_name: ldapserver
    ports:
      - '1389:1389'
      - '1636:1636'
    image: bitnami/openldap:2
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks:
      my_net:
        ipv4_address: 172.16.243.7
    #volumes:
networks:
  my_net:
    driver: bridge
    ipam:
      config:
        - subnet: "172.16.243.0/24"
          gateway: "172.16.243.1"
